phase4/social_network/social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from social_network_app import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('', include('social_network_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phase4/social_network/social_network_app/urls.py
from django.urls import path
from social_network_app import views
from django.conf.urls import url

app_name = 'social_network_app'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('verification/', views.VerificationView.as_view(), name='verification'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('friendships/', views.FriendsView.as_view(), name='friendships'),
    path('users/<int:user_id>/', views.UsersView.as_view(), name='users'),
    path('borrow_requests/', views.BorrowRequestsView.as_view(), name='borrow_requests'),
    path('all_items/', views.AllItemsView.as_view(), name='all_items'),
    path('all_users/', views.AllUsersView.as_view(), name='all_users'),
    path('notifications/', views.NotificationsView.as_view(), name='notifications'),
    path('announcements/', views.AnnouncementsView.as_view(), name='announcements'),
    path('item/<int:item_id>/', views.ItemView.as_view(), name='item'),

    #     for AJAX calls
    url(r'^see_announcement/$', views.see_announcement, name='see-announcement'),
    url(r'^see_notification/$', views.see_notification, name='see-notification'),
]

phase4/social_network/social_network_app/models.py
from django.db import models
from django.contrib.auth.models import User

WATCH_REQUEST_TYPES = {
    0: "COMMENT",
    1: "BORROW",
    2: "USER",

}
STATE = {
    0: "Pending",
    1: "Close Friend",
    2: "Friend",
}
STATE_TYPE = {
    0: "CLOSED",
    1: "CLOSEFRIEND",
    2: "FRIEND",
    3: "EVERYONE",
}


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    verification_code = models.CharField(max_length=150)


class Item(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    isbn = models.IntegerField(null=True, blank=True)
    artist = models.CharField(max_length=256)
    genre = models.CharField(max_length=150)
    year = models.IntegerField()
    location = models.CharField(max_length=256)
    view = models.IntegerField(default=2)
    detail = models.IntegerField(default=2)
    borrow = models.IntegerField(default=2)
    comment = models.IntegerField(default=2)
    search = models.IntegerField(default=2)

    def __str__(self):
        return "owner : " + str(self.owner) + " title : " + str(self.id)  +self.title


class Friend(models.Model):
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_sender_user')
    receiver_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_receiver_user')
    state = models.IntegerField(default=0)

    class Meta:
        unique_together = ('sender_user', 'receiver_user',)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_user')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='%(class)s_item')
    text = models.TextField()
    date = models.DateTimeField()


class Announcement(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    friend_state = models.IntegerField()
    msg = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class WatchRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    watch_method = models.IntegerField()
    followed_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followed_user', null=True)


class Borrow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_user')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='%(class)s_item')
    taken_date = models.DateTimeField()
    returned_date = models.DateTimeField()
    rate = models.IntegerField(null=True)
    is_returned = models.BooleanField(default=0)


class BorrowRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    request_date = models.DateTimeField()


class Notification(models.Model):
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender_user')
    receiver_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver_user')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    date = models.DateTimeField()

phase4/social_network/social_network_app/forms.py
from django.contrib.auth.models import User
from social_network_app.models import *
from  django import forms


class UserForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First Name'}), label='', required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last Name'}), label='', required=True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email Address'}), label='', required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), label='', required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password')


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email Address'}), label='', max_length=254, required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),  label='', max_length=128, required=True)


class VerificationForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email Address'}), label='', max_length=254, required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),  label='', max_length=128, required=True)
    verification = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Verification Number'}),  label='', max_length=128, required=True)

phase4/social_network/social_network_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from social_network_app import forms
from django.urls import reverse
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.db.models import Q
from isbnlib import meta
from datetime import datetime, timedelta
from secrets import token_hex
from django.contrib import messages
import string
from random import *
from django.core.mail import send_mail

user_verification_dict = {}


class IndexView(View):
    def get(self, request):
        items = {}
        if request.user.id:
            items = Item.objects.filter(owner=request.user)
        return render(request, 'index.html', {'items': items})

    def post(self, request):
        old_pass = request.POST['old_password']
        new_pass = request.POST['new_password']
        usr = User.objects.get(pk=request.user.id)
        if old_pass != "":
            if usr.check_password(old_pass):
                usr.set_password(new_pass)
                usr.save()

                return redirect("/")
            else:
                messages.warning(request, "Wrong Password, if you want to get new password, please do not fill old password field.")
                return redirect("/")
        else:
            characters = string.ascii_letters + string.punctuation + string.digits
            generated_password = "".join(choice(characters) for x in range(randint(8, 16)))
            usr.set_password(generated_password)
            usr.save()
            print("Generated Password : ",generated_password)

            return redirect("/")


class RegisterView(View):
    user_form = forms.UserForm()

    def get(self, request):
        return render(request, 'register.html', {'user_form': self.user_form})

    def post(self, request):
        self.user_form = forms.UserForm(data=request.POST)
        if self.user_form.is_valid():
            user = self.user_form.save(commit=False)
            user.set_password(self.user_form.cleaned_data['password'])
            user.username = self.user_form.cleaned_data['email'].lower()
            user.is_active = False
            user.save()
            characters = string.ascii_letters + string.punctuation + string.digits
            generated_password = token_hex(16)
            # user_verification_dict[user] = generated_password
            profile = Profile.objects.create(user=user, verification_code=generated_password)
            send_mail(
                'Social Network Verification Code',
                "Your verification code is " + generated_password,
                'besteburhan7@gmail.com',
                [user.email, ],
                fail_silently=False,
            )
            print("You registered successfully. Please use the verification number to log-in. Verification number: ", generated_password)
            return HttpResponseRedirect(reverse('social_network_app:verification'))
        else:
            print(self.user_form.errors)
            return render(request, 'register.html', {'user_form': self.user_form})


class LoginView(View):
    login_form = forms.LoginForm()

    def get(self, request):
        return render(request, 'login.html', {'login_form': self.login_form})

    def post(self, request):
        self.login_form = forms.LoginForm(data=request.POST)
        try:
            usr = User.objects.get(email=request.POST['email'])

        except:
            print('Login failed')
            return HttpResponse("invalid login details")
        if self.login_form.is_valid() and usr.is_active:
            user = authenticate(username=self.login_form.cleaned_data['email'], password=self.login_form.cleaned_data['password'])
            if user and user.is_active:
                login(request, user)
                return redirect('/')
            else:
                return HttpResponse("invalid login details")
        else:
            print('Login failed')
            return HttpResponse("invalid login details")


class VerificationView(View):
    verification_form = forms.VerificationForm()

    def get(self, request):
        return render(request, 'verification.html', {'verification_form': self.verification_form})

    def post(self, request):
        self.verification_form = forms.VerificationForm(data=request.POST)
        try:
            usr = User.objects.get(email=request.POST['email'])

        except:
            return HttpResponse("invalid verification details")
        if usr.profile_set.get().verification_code == request.POST['verification'] and usr.check_password(request.POST['password']):
            usr.is_active = 1
            usr.save()
            return redirect('/login/')

        else:
            messages.warning(request, "Verification failed.")
            return redirect('/verification/')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


class UsersView(View):
    def get(self, request, user_id):
        location_available_items = {}
        location_unavailable_items = {}
        borrow_requests = {}
        usr = User.objects.get(id=user_id)
        if user_id:
            if request.user.id != user_id:
                # location null if it is borrowed
                try:
                    br = Borrow.objects.filter(is_returned=0).values_list('item', flat=True)
                except:
                    br = []
                friend_state = 0
                try:
                    friend_state = Friend.objects.get((Q(sender_user=user_id ) & Q(receiver_user=request.user)) | (Q(receiver_user=user_id ) & Q(sender_user=request.user))).state
                except:
                    pass
                if friend_state == 0:
                    location_available_items = Item.objects.filter(Q(owner=user_id) & Q(view=3) & ~Q(id__in=br))
                    location_unavailable_items = Item.objects.filter(Q(owner=user_id) & Q(view=3) & Q(id__in=br))
                else:
                    location_available_items = Item.objects.filter(Q(owner=user_id) & Q(view__gte=friend_state) & ~Q(id__in=br))
                    location_unavailable_items = Item.objects.filter(Q(owner=user_id) & Q(view__gte=friend_state) & Q(id__in=br))
            else:  # own items

                location_available_items = Item.objects.filter(Q(owner=request.user))


        return render(request, 'users.html', {'location_unavailable_items': location_unavailable_items, 'location_available_items': location_available_items,
                                                        'borrow_requests': borrow_requests, 'user_viewed':usr})

    def post(self, request, user_id):

        if user_id == request.user.id:
            if request.POST['submit_type'] == 'save':
                item = Item()
                item.owner_id = int(user_id)
                item.type = request.POST['type']
                item.title = request.POST['title']
                item.artist = request.POST['artist']
                item.genre = request.POST['genre']
                item.year = request.POST['year']
                item.location = request.POST['location']
                item.view = request.POST['view']
                item.detail = request.POST['detail']
                item.borrow = request.POST['borrow']
                item.comment = request.POST['comment']
                item.search = request.POST['search']
                if request.POST['isbn'] != '':
                    metadata = None
                    try:

                        metadata = meta(isbn=str(request.POST['isbn']))
                    except:
                        messages.warning(request, 'ISBN Number is wrong! Item couldn\'t be added' )
                        return redirect('/users/' + str(user_id))
                    if metadata is None:
                        messages.warning(request, 'Meta data couldn\'t be obtained' )
                        return redirect('/users/' + str(user_id))
                    else:
                        item.title = metadata['Title']
                        item.year = metadata['Year']
                        item.artist = metadata['Authors'][0]

                if item.detail > item.view:
                    item.view = item.detail
                    messages.warning(request, 'Detail permission cannot have higher priority than view permission. View permission also be set ' + STATE_TYPE[int(item.detail)])

                if item.borrow > item.view:
                    item.borrow = item.view
                    messages.warning(request, 'Borrow permission cannot have higher priority than view permission. Borrow permission also be set ' + STATE_TYPE[int(item.view)])

                # if item.detail > item.comment:
                #     item.comment = item.detail
                #     messages.warning(request, 'Detail permission cannot have higher priority than comment permission. Comment permission also be set ' + STATE_TYPE[int(item.detail)])
                item.save()

                watch_requests = WatchRequest.objects.filter(Q(followed_user=request.user) & Q(watch_method=2))
                text = f'{request.user.first_name} {request.user.last_name} added new item -> with title : {item.title}'
                for wr in watch_requests:
                    Notification.objects.create(sender_user=request.user, receiver_user=wr.user, text=text, date=datetime.now())

                messages.success(request, 'Item is added successfully.')
                return redirect('/users/' + str(user_id))
            elif request.POST['submit_type'] == 'returned':
                borrow_item = Borrow.objects.get(item_id=request.POST['item_id'], is_returned=0)
                borrow_item.is_returned = 1
                borrow_item.save()

phase4/social_network/social_network_app/templates/all_items.html
{% extends 'base.html' %}

{% load extras %}
{% block block_for_authenticated_users %}
    <div style="margin: 10px 120px 10px 120px;">
        <table class="table table-striped">
    <h4>ITEMS</h4>
    <br>
    <thead>
      <tr>
	      <th> Title </th>
	      <th> Type</th>
	      <th> Genre </th>
	      <th> Artist </th>
	      <th> Year </th>
          <th></th>
      </tr>
    </thead>
    <tbody>
	{% for item in borrowable_items %}
		<tr>
			<td><a href="/item/{{ item.id }}/">{{ item.title}}</a></td>
			<td>{{ item.type }}</td>
			<td>{{ item.genre }}</td>
			<td>{{ item.artist }}</td>
			<td>{{ item.year }}</td>
            {% check_borrow_permission request.user item as is_borrowable%}
            {% if is_borrowable %}
            <td>
                <div class="form-group col-sm-4" >
                         <form action="/all_items/" method="post">
                             {% csrf_token %}
                             <div class="col-sm-10" style="margin-top: -20px">
                                 <input name="item_id" type="text" hidden value="{{ item.id }}">
                                <label for="states"></label>

                             </div>
                                <div class="col-sm-2">
                             <button type="submit" class="btn btn-warning" name="submit_type" value="borrow"> Borrow </button>
                                </div>
                        </form>
                     </div>
            </td>
        {% endif %}

		</tr>
	{% endfor %}
    {% for item in  viewable_items%}
		<tr>
			<td><a href="/item/{{ item.id }}/">{{ item.title}}</a></td>
			<td>{{ item.type }}</td>
			<td>{{ item.genre }}</td>
			<td>{{ item.artist }}</td>
			<td>{{ item.year }}</td>

		</tr>
	{% endfor %}

    </tbody>
  </table>
        <br>
        <div style="float: right;">
            <form class="form-inline my-2 my-lg-0" method="POST" action="/all_items/">
                {% csrf_token %}
                <input type="checkbox" aria-label="Checkbox for following text input" id="for_borrow" name="for_borrow" >
                <label for="for_borrow" style="margin-left: 10px; margin-right: 10px;" > To borrow</label>
                  <input class="form-control mr-sm-2" type="text" name="search_text"  placeholder="in title and artist" aria-label="Search" required>
                  <input class="form-control mr-sm-2" type="text" name="genre"  placeholder="in genre" aria-label="Search">
                  <input class="form-control mr-sm-2" type="number" name="year"  placeholder="after what year" aria-label="Search">
                  <button class="btn btn-outline-warning my-2 my-sm-0" type="submit" name="submit_type" value="search">Search</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block block_for_unauthenticated_users %}
    <h2>hooooop nabıyon</h2>
{% endblock %}

phase4/social_network/social_network_app/templates/announcements.html
{% extends 'base.html' %}

{% load extras %}
{% block block_for_authenticated_users %}
    <div style="margin: 10px 120px 10px 120px">
        <h3> Announcements</h3>
        <table class="table table-striped">
    <br>
    <thead>
      <tr>
	      <th> From </th>
	      <th> Item </th>
	      <th> Announcement</th>
	      <th> Date </th>
      </tr>
    </thead>
    <tbody>
	{% for announcement in announcements %}
		<tr>
			<td><a href="/users/{{ announcement.item.owner.id }}/">{{ announcement.item.owner.first_name|capfirst}} {{ announcement.item.owner.last_name|capfirst }}</a></td>
			<td><a href="/item/{{ announcement.item.id }}/">{{ announcement.item.title|capfirst}}</a></td>
			<td>{{ announcement.msg }}</td>
			<td>{{ announcement.date }}</td>

		</tr>
	{% endfor %}


    </tbody>
  </table>
    </div>
{% endblock %}

{% block block_for_unauthenticated_users %}
    <h2>hooooop nabıyon</h2>
{% endblock %}

phase4/social_network/social_network_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
  <head>
    <meta charset="utf-8">
       <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{%static 'css/base.css'%}">

    <title>
        {% block title %}
        {% endblock %}
    </title>


    {%block head%}
    {%endblock%}
        <script
          src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
          integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
          crossorigin="anonymous"></script>
         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="shortcut icon" type="image/x-icon" href="{%static 'media/download.png'%}"/>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
      <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
         <link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">
        <link href="https://cdn.materialdesignicons.com/4.7.95/css/materialdesignicons.min.css" rel="stylesheet">
{#      <link href="https://fonts.googleapis.com/css?family=Roboto:900&display=swap" rel="stylesheet">#}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


      <script>
        var announceSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/announcement/' );

        announceSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var announcement_id = data['announcement_id'];
            console.log("Mesaj alındıııı; ",data );
            $.ajax({
                type: 'get',
                url: "{% url 'social_network_app:see-announcement'  %}",
                data: {
                    'announcement_id': announcement_id,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function (response) {
                    console.log(response);
                    if (response['message'] != "") {

                        $('#notifications').text(response['message'])
                            .css({
                                position: "fixed", bottom: "5px",
                                right: "5px", padding: "15px", "border-radius": "8px",
                                "box-shadow": "4px 4px 2px #808080", 'background-color': "#ffa0a0"
                            })
                            .fadeIn().delay(3000).slideUp();
                    }

                },
                error: function (data) {
                  alert("error ");
                },
            });
        };

        announceSocket.onclose = function(e) {
            console.error('Announcement socket closed unexpectedly');
        };

      </script>


  <script>
        var notificationSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/notification/' );

        notificationSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var notification_id = data['notification_id'];
            $.ajax({
                type: 'get',
                url: "{% url 'social_network_app:see-notification'  %}",
                data: {
                    'notification_id': notification_id,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function (response) {
                    console.log(response);
                    if (response['message'] != "") {

                        $('#notifications').text(response['message'])
                            .css({
                                position: "fixed", bottom: "5px",
                                right: "5px", padding: "15px", "border-radius": "8px",
                                "box-shadow": "4px 4px 2px #808080", 'background-color': "#ffa0a0"
                            })
                            .fadeIn().delay(3000).slideUp();
                    }

                },
                error: function (data) {
                  alert("error ");
                },
            });
        };

        notificationSocket.onclose = function(e) {
            console.error('Notification socket closed unexpectedly');
        };

      </script>



  </head>

  <body>


      <nav class="navbar navbar-expand-lg navbar-light " id="navigation-bar" >
      {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'index' %}">{{user.first_name|capfirst}} {{user.last_name|capfirst}}</a>

      {% else %}
          <a class="navbar-brand" href="{% url 'index' %}" > Online Book and Media Sharing </a>
      {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto" >
{#                #}
                {% if user.is_authenticated %}

              <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Actions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'social_network_app:users' request.user.pk %}" >
                                My Items
                            </a>
                        <a class="dropdown-item" href="{% url 'social_network_app:friendships'  %}" >
                                Friends
                            </a>
                        <a class="dropdown-item" href="{% url 'social_network_app:borrow_requests' %}" >
                                Borrows & Requests
                            </a>
                        <a class="dropdown-item" href="{% url 'social_network_app:all_items' %}" >
                                All Items
                            </a>
                        <a class="dropdown-item" href="{% url 'social_network_app:all_users' %}" >
                                All Users
                            </a>
                        <a class="dropdown-item" href="{% url 'social_network_app:notifications' %}" >
                                Notifications
                            </a>
                        <a class="dropdown-item" href="{% url 'social_network_app:announcements' %}" >
                                Announcements
                            </a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Change Password</a>
                    </div>
              </li>

                  {%endif%}

            </ul>
            <ul class="navbar-nav ml-auto" >
{#                #}
                {% if user.is_authenticated %}

                  <li class="nav-item">
                        <a class="nav-link" href="{%url 'social_network_app:logout' %}"  >
                            <span class="mdi mdi-logout"></span> Logout</a>
                      </li>
                  {%else%}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'social_network_app:register' %}" >
                              <span class="mdi mdi-account-plus"></span>
                      <span class="glyphicon glyphicon-user" ></span> Sign Up</a>
                    </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'social_network_app:verification' %}" >
                      <span class="mdi mdi-shield-check"></span></span> Verify account </a>
                    </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{%url 'social_network_app:login' %}" ><span class="mdi mdi-login"></span></span> Sign In</a>
                      </li>
                  {%endif%}

            </ul>

          </div>
        </nav>

    {#####################################}

   {%if user.is_authenticated%}
    <div class="bg">
            <div class="container-fluid ">
            {# #################### #}


                        {% block block_for_authenticated_users%}
                        {%endblock%}

            </div>
            <div id="notifications"></div>
    </div>
  {% else %}
        {%block block_for_unauthenticated_users %}
        {% endblock %}
  {% endif %}
  </body>
</html>

phase4/social_network/social_network_app/templates/register.html
{% extends 'base.html'%}
{% load static %}
{% block head %}


    <link rel="stylesheet" href="{%static 'css/form.css'%}">

{% endblock %}

{%block block_for_unauthenticated_users%}

    <div class="bg" >
        <div class="container">
            <div class="item">
               <h4 style="color: #ffffff">Sign Up</h4>
                <p style="text-align: center;">
               <div class="flex-form">
                  <form enctype="multipart/form-data" method="post">
                     {% csrf_token %}
                    {{user_form.as_p}}
                      <button type="submit" value="Register" style="color: white">SIGN UP</button>
                  </form>
               </div>
                </p>
                  <p class="reg">Already registered? <a href="{%url 'social_network_app:login' %}" style="color: #ffffff">Sign In</a></p>
            </div>
        </div>


</div>

{% endblock %}